[package]
name = "lambdamux-macro"
version = "1.0.3"
edition = "2021"
description = "Procedural macros for declaring lambdamux routes"
license = "GPL-3.0-only OR Apache-2.0"
repository = "https://github.com/anuradhawick/rs_template"
readme = "README.md"
keywords = ["aws", "lambda", "router", "macro", "proc-macro"]
categories = ["web-programming", "development-tools::procedural-macro-helpers"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.79"
quote = "1.0.35"
syn = { version = "3.0.3", features = ["full"] }
