[package]
name = "router_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.79"
quote = "1.0.35"
syn = { version = "2.0.58", features = ["full"] }
router_container = { path = "../router_container"}
ctor = "0.2.7"
